apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dep
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: devopshint/node-app:latest
        ports:
        - containerPort: {testPort}
---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-service
spec:
  selector:
    app: demo
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {testPort}
    targetPort: {testPort}
    nodePort: {testNodePort}
